using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using YuGhiOhBattleHandler.Interfaces;
//using YuGhiOhBattleHandler.Game.Interfaces;

namespace YuGhiOhBattleHandler
{
    public enum effect_types
    {
        EFFECT_TYPE_SINGLE = 0x0001,
        EFFECT_TYPE_FIELD = 0x0002,
        EFFECT_TYPE_EQUIP = 0x0004,
        EFFECT_TYPE_ACTIONS = 0x0008,
        EFFECT_TYPE_ACTIVATE = 0x0010,
        EFFECT_TYPE_FLIP = 0x0020,
        EFFECT_TYPE_IGNITION = 0x0040,
        EFFECT_TYPE_TRIGGER_O = 0x0080,
        EFFECT_TYPE_QUICK_O = 0x0100,
        EFFECT_TYPE_TRIGGER_F = 0x0200,
        EFFECT_TYPE_QUICK_F = 0x0400,
        EFFECT_TYPE_CONTINOUS = 0x0800
    }
    public enum effect_flag
    {
        EFFECT_FLAG_INITIAL = 0x0001,
        EFFECT_FLAG_FUNC_VALUE = 0x0002,
        EFFECT_FLAG_COUNT_LIMIT = 0x0004,
        EFFECT_FLAG_FIELD_ONLY = 0x0008,
        EFFECT_FLAG_CARD_TARGET = 0x0010,
        EFFECT_FLAG_IGNORE_RANGE = 0x0020,
        EFFECT_FLAG_ABSOLUTE_TARGET = 0x0040,
        EFFECT_FLAG_IGNORE_IMMUNE = 0x0080,
        EFFECT_FLAG_SET_AVAILABLE = 0x0100,
        EFFECT_FLAG_CANNOT_NEGATE = 0x0200,
        EFFECT_FLAG_CANNOT_DISABLE = 0x0400,
        EFFECT_FLAG_PLAYER_TARGET = 0x0800,
        EFFECT_FLAG_BOTH_SIDE = 0x1000,
        EFFECT_FLAG_COPY_INHERIT = 0x2000,
        EFFECT_FLAG_DAMAGE_STEP = 0x4000,
        EFFECT_FLAG_DAMAGE_CAL = 0x8000,
        EFFECT_FLAG_DELAY = 0x10000,
        EFFECT_FLAG_SINGLE_RANGE = 0x20000,
        EFFECT_FLAG_UNCOPYABLE = 0x40000,
        EFFECT_FLAG_OATH = 0x80000,
        EFFECT_FLAG_SPSUM_PARAM = 0x100000,
        EFFECT_FLAG_REPEAT = 0x200000,
        EFFECT_FLAG_NO_TURN_RESET = 0x400000,
        EFFECT_FLAG_EVENT_PLAYER = 0x800000,
        EFFECT_FLAG_OWNER_RELATE = 0x1000000,
        EFFECT_FLAG_AVAILABLE_BD = 0x2000000,
        EFFECT_FLAG_CLIENT_HINT = 0x4000000,
        EFFECT_FLAG_CHAIN_UNIQUE = 0x8000000,
        EFFECT_FLAG_CVAL_CHECK = 0x40000000,
    }

    public enum effect_codes
    {
        EFFECT_IMMUNE_EFFECT,
        EFFECT_DISABLE,
        EFFECT_CANNOT_DISABLE,
        EFFECT_SET_CONTROL,
        EFFECT_CANNOT_CHANGE_CONTROL,
        EFFECT_CANNOT_ACTIVATE,
        EFFECT_CANNOT_TRIGGER,
        EFFECT_DISABLE_EFFECT,
        EFFECT_DISABLE_CHAIN,
        EFFECT_DISABLE_TRAPMONSTER,
        EFFECT_CANNOT_INACTIVATE,
        EFFECT_CANNOT_DISEFFECT,
        EFFECT_CANNOT_CHANGE_POSITION,
        EFFECT_TRAP_ACT_IN_HAND,
        EFFECT_TRAP_ACT_IN_SET_TURN,
        EFFECT_REMAIN_FIELD,
        EFFECT_MONSTER_SSET,
        EFFECT_CANNOT_SUMMON,
        EFFECT_CANNOT_FLIP_SUMMON,
        EFFECT_CANNOT_SPECIAL_SUMMO,
        EFFECT_CANNOT_MSET,
        EFFECT_CANNOT_SSET,
        EFFECT_CANNOT_DRAW,
        EFFECT_CANNOT_DISABLE_SUM,
        EFFECT_CANNOT_DISABLE_SPSUMMO,
        EFFECT_SET_SUMMON_COUNT_LIMIT,
        EFFECT_EXTRA_SUMMON_COUNT,
        EFFECT_SPSUMMON_CONDITION,
        EFFECT_REVIVE_LIMIT,
        EFFECT_SUMMON_PROC,
        EFFECT_LIMIT_SUMMON_PROC,
        EFFECT_SPSUMMON_PROC,
        EFFECT_EXTRA_SET_COUNT,
        EFFECT_SET_PROC,
        EFFECT_LIMIT_SET_PROC,
        EFFECT_DEVINE_LIGHT,
        EFFECT_CANNOT_DISABLE_FLIP_SUMMON,
        EFFECT_INDESTRUCTABLE,
        EFFECT_INDESTRUCTABLE_EFFECT,
        EFFECT_INDESTRUCTABLE_BATTLE,
        EFFECT_UNRELEASABLE_SUM,
        EFFECT_UNRELEASABLE_NONSUM,
        EFFECT_DESTROY_SUBSTITUTE,
        EFFECT_CANNOT_RELEASE,
        EFFECT_INDESTRUCTABLE_COUNT,
        EFFECT_UNRELEASABLE_EFFECT,
        EFFECT_DESTROY_REPLACE,
        EFFECT_RELEASE_REPLACE,
        EFFECT_SEND_REPLACE,
        EFFECT_CANNOT_DISCARD_HAND,
        EFFECT_CANNOT_DISCARD_DECK,
        EFFECT_CANNOT_USE_AS_COST,
        EFFECT_CANNOT_PLACE_COUNTER,
        EFFECT_LEAVE_FIELD_REDIRECT,
        EFFECT_TO_HAND_REDIRECT,
        EFFECT_TO_DECK_REDIRECT,
        EFFECT_TO_GRAVE_REDIRECT,
        EFFECT_REMOVE_REDIRECT,
        EFFECT_CANNOT_TO_HAND,
        EFFECT_CANNOT_TO_DECK,
        EFFECT_CANNOT_REMOVE,
        EFFECT_CANNOT_TO_GRAVE,
        EFFECT_CANNOT_TURN_SET,
        EFFECT_CANNOT_BE_BATTLE_TARGET,
        EFFECT_CANNOT_BE_EFFECT_TARGET,
        EFFECT_IGNORE_BATTLE_TARGET,
        EFFECT_CANNOT_DIRECT_ATTACK,
        EFFECT_DIRECT_ATTACK,
        EFFECT_DUAL_STATUS,
        EFFECT_EQUIP_LIMIT,
        EFFECT_DUAL_SUMMONABLE,
        EFFECT_REVERSE_DAMAGE,
        EFFECT_REVERSE_RECOVER,
        EFFECT_CHANGE_DAMAGE,
        EFFECT_REFLECT_DAMAGE,
        EFFECT_CANNOT_ATTACK,
        EFFECT_CANNOT_ATTACK_ANNOUNCE,
        EFFECT_CANNOT_CHANGE_POS_E,
        EFFECT_ACTIVATE_COST,
        EFFECT_SUMMON_COST,
        EFFECT_SPSUMMON_COST,
        EFFECT_FLIPSUMMON_COST,
        EFFECT_MSET_COST,
        EFFECT_SSET_COST,
        EFFECT_ATTACK_COST,
        EFFECT_UPDATE_ATTACK,
        EFFECT_SET_ATTACK,
        EFFECT_SET_ATTACK_FINAL,
        EFFECT_SET_DEFENSE,
        EFFECT_SET_BASE_ATTACK,
        EFFECT_UPDATE_DEFENSE,
        EFFECT_SET_DEFENSE_FINAL,
        EFFECT_SET_BASE_DEFENSE,
        EFFECT_REVERSE_UPDATE,
        EFFECT_SWAP_AD,
        EFFECT_SWAP_BASE_AD,
        EFFECT_SWAP_ATTACK_FINAL,
        EFFECT_SWAP_DEFENSE_FINAL,
        EFFECT_ADD_CODE,
        EFFECT_CHANGE_CODE,
        EFFECT_ADD_TYPE,
        EFFECT_REMOVE_TYPE,
        EFFECT_CHANGE_TYPE,
        EFFECT_ADD_RACE,
        EFFECT_REMOVE_RACE,
        EFFECT_CHANGE_RACE,
        EFFECT_ADD_ATTRIBUTE,
        EFFECT_REMOVE_ATTRIBUTE,
        EFFECT_CHANGE_ATTRIBUTE,
        EFFECT_UPDATE_LEVEL,
        EFFECT_CHANGE_LEVEL,
        EFFECT_UPDATE_RANK,
        EFFECT_CHANGE_RANK,
        EFFECT_SET_POSITION,
        EFFECT_SELF_DESTROY,
        EFFECT_SELF_TOGRAVE,
        EFFECT_DOUBLE_TRIBUTE,
        EFFECT_DECREASE_TRIBUTE,
        EFFECT_DECREASE_TRIBUTE_SET,
        EFFECT_EXTRA_RELEASE,
        EFFECT_TRIBUTE_LIMIT,
        EFFECT_EXTRA_RELEASE_SUM,
        EFFECT_PUBLIC,
        EFFECT_COUNTER_PERMIT,
        EFFECT_COUNTER_LIMIT,
        EFFECT_RCOUNTER_REPLACE,
        EFFECT_LPCOST_CHANGE,
        EFFECT_LPCOST_REPLACE,
        EFFECT_SKIP_DP,
        EFFECT_SKIP_SP,
        EFFECT_SKIP_M1,
        EFFECT_SKIP_BP,
        EFFECT_SKIP_M2,
        EFFECT_CANNOT_BP,
        EFFECT_CANNOT_M2,
        EFFECT_CANNOT_EP,
        EFFECT_SKIP_TURN,
        EFFECT_DEFENSE_ATTACK,
        EFFECT_MUST_ATTACK,
        EFFECT_FIRST_ATTACK,
        EFFECT_ATTACK_ALL,
        EFFECT_EXTRA_ATTACK,
        EFFECT_MUST_BE_ATTACKED,
        EFFECT_ONLY_BE_ATTACKED,
        EFFECT_ATTACK_DISABLED,
        EFFECT_NO_BATTLE_DAMAGE,
        EFFECT_AVOID_BATTLE_DAMAGE,
        EFFECT_REFLECT_BATTLE_DAMAGE,
        EFFECT_PIERCE,
        EFFECT_BATTLE_DESTROY_REDIRECT,
        EFFECT_BATTLE_DAMAGE_TO_EFFECT,
        EFFECT_TOSS_COIN_REPLACE,
        EFFECT_TOSS_DICE_REPLACE,
        EFFECT_FUSION_MATERIAL,
        EFFECT_CHAIN_MATERIAL,
        EFFECT_FUSION_SUBSTITUTE,
        EFFECT_CANNOT_BE_FUSION_MATERIAL,
        EFFECT_RITUAL_LEVEL,
        EFFECT_EXTRA_RITUAL_MATERIAL,
        EFFECT_OVERLAY_REMOVE_REPLACE,
        EFFECT_SCRAP_CHIMERA,
        EFFECT_TUNE_MAGICIAN_X,
        EFFECT_PRE_MONSTER,
        EFFECT_MATERIAL_CHECK,
        EFFECT_DISABLE_FIELD,
        EFFECT_USE_EXTRA_MZONE,
        EFFECT_USE_EXTRA_SZONE,
        EFFECT_MAX_MZONE,
        EFFECT_MAX_SZONE,
        EFFECT_HAND_LIMIT,
        EFFECT_DRAW_COUNT,
        EFFECT_SPIRIT_DONOT_RETURN,
        EFFECT_SPIRIT_MAYNOT_RETURN,
        EFFECT_CHANGE_ENVIRONMENT,
        EFFECT_NECRO_VALLEY,
        EFFECT_FORBIDDEN,
        EFFECT_NECRO_VALLEY_IM,
        EFFECT_REVERSE_DECK,
        EFFECT_REMOVE_BRAINWASHING,
        EFFECT_BP_TWICE,
        EFFECT_UNIQUE_CHECK,
        EFFECT_MATCH_KILL,
        EFFECT_QP_ACT_IN_NTPHAND,
        EFFECT_MUST_BE_SMATERIAL,
        EFFECT_TO_GRAVE_REDIRECT_CB,
        EFFECT_CHANGE_LEVEL_FINAL,
        EFFECT_CHANGE_RANK_FINAL,
        EFFECT_SPSUMMON_PROC_G,
        EFFECT_SPSUMMON_COUNT_LIMIT,
        EFFECT_LEFT_SPSUMMON_COUNT,
        EFFECT_CANNOT_SELECT_BATTLE_TARGET,
        EFFECT_CANNOT_SELECT_EFFECT_TARGET,
        EFFECT_ADD_SETCODE,
        EFFECT_NO_EFFECT_DAMAGE,
        EFFECT_UNSUMMONABLE_CARD,
        EFFECT_DISABLE_CHAIN_FIELD,
        EFFECT_DISCARD_COST_CHANGE,
        EFFECT_ADD_FUSION_CODE,
        EFFECT_ADD_FUSION_SETCODE,
        EFFECT_RISE_TO_FULL_HEIGHT,
        EFFECT_ONLY_ATTACK_MONSTER,
        EFFECT_MUST_ATTACK_MONSTER,
        EFFECT_PATRICIAN_OF_DARKNESS,
        EFFECT_EXTRA_ATTACK_MONSTER,
        EFFECT_UNION_STATUS,
        EFFECT_OLDUNION_STATUS,
        EFFECT_ADD_FUSION_ATTRIBUTE,
        EFFECT_REMOVE_FUSION_ATTRIBUTE,
        EFFECT_CHANGE_FUSION_ATTRIBUTE,
        EFFECT_EXTRA_FUSION_MATERIAL,
        EVENT_STARTUP,
        EVENT_FLIP,
        EVENT_FREE_CHAIN,
        EVENT_DESTROY,
        EVENT_REMOVE,
        EVENT_TO_HAND,
        EVENT_TO_DECK,
        EVENT_TO_GRAVE,
        EVENT_LEAVE_FIELD,
        EVENT_CHANGE_POS,
        EVENT_RELEASE,
        EVENT_DISCARD,
        EVENT_LEAVE_FIELD_P,
        EVENT_CHAIN_SOLVING,
        EVENT_CHAIN_ACTIVATING,
        EVENT_CHAIN_SOLVED,
        EVENT_CHAIN_ACTIVATED,
        EVENT_CHAIN_NEGATED,
        EVENT_CHAIN_DISABLED,
        EVENT_CHAIN_END,
        EVENT_CHAINING,
        EVENT_BECOME_TARGET,
        EVENT_DESTROYED,
        EVENT_ADJUST,
        EVENT_SUMMON_SUCCESS,
        EVENT_FLIP_SUMMON_SUCCESS,
        EVENT_SPSUMMON_SUCCESS,
        EVENT_SUMMON,
        EVENT_FLIP_SUMMON,
        EVENT_SPSUMMON,
        EVENT_MSET,
        EVENT_SSET,
        EVENT_BE_MATERIAL,
        EVENT_BE_PRE_MATERIAL,
        EVENT_DRAW,
        EVENT_DAMAGE,
        EVENT_RECOVER,
        EVENT_PREDRAW,
        EVENT_CONTROL_CHANGED,
        EVENT_EQUIP,
        EVENT_ATTACK_ANNOUNCE,
        EVENT_BE_BATTLE_TARGET,
        EVENT_BATTLE_START,
        EVENT_BATTLE_CONFIRM,
        EVENT_PRE_DAMAGE_CALCULATE,
        EVENT_DAMAGE_CALCULATING,
        EVENT_PRE_BATTLE_DAMAGE,
        EVENT_BATTLE_END,
        EVENT_BATTLED,
        EVENT_BATTLE_DESTROYING,
        EVENT_BATTLE_DESTROYED,
        EVENT_DAMAGE_STEP_END,
        EVENT_ATTACK_DISABLED,
        EVENT_BATTLE_DAMAGE,
        EVENT_TOSS_DICE,
        EVENT_TOSS_COIN,
        EVENT_TOSS_COIN_NEGATE,
        EVENT_TOSS_DICE_NEGATE,
        EVENT_LEVEL_UP,
        EVENT_PAY_LPCOST,
        EVENT_DETACH_MATERIAL,
        EVENT_RETURN_TO_GRAVE,
        EVENT_TURN_END,
        EVENT_PHASE,
        EVENT_PHASE_START,
        EVENT_ADD_COUNTER,
        EVENT_REMOVE_COUNTER,
        EVENT_CUSTOM
    }
    public class Effect : BaseEffect
    {
        private Duel duel;
        private int code;
        public int Code
        {
            get { return code; }
            set { code = value; }
        }
        private int type;
        public int Type
        {
            get { return type; }
            set { type = value; }
        }
        private int flag;
        public int Flag
        {
            get { return flag; }
            set { flag = value; }
        }
        private int id;
        public int ID
        {
            get { return id; }
            set { id = value; }
        }
        

        public Effect(Duel duel)
        {
            this.duel = duel;
        }

        public bool IsAvailable()
        {
            return true;
        }

        public bool IsFlag(int flag)
        {
            return true;
        }

        public bool IsImmuned(Card card)
        {
            throw new NotImplementedException();
        }

        public bool IsTarget(Card card)
        {
            throw new NotImplementedException();
        }

        public int GetValue(Card card)
        {
            throw new NotImplementedException();
        }
    }
}
